apiVersion: demo.example.org/v1alpha1
kind: XWebApp
metadata:
  name: my-web
  namespace: worldcup
spec:
  image: nginx:1.27
  replicas: 2
  ports: 80
  crossplane:
    compositionRef:
      name: xwebapp-deployment
