apiVersion: platform.dangaiden.com/v1
kind: Website
metadata:
  name: my-web
  namespace: worldcup
spec:
  image: nginx:1.27
  crossplane:
    compositionRef:
      name: website-deployment
