apiVersion: platform.dangaiden.com/v1
kind: Website
metadata:
  name: my-web
  namespace: worldcup
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  image: nginx:1.27
  crossplane:
    compositionRef:
      name: website-deployment
